name: monocular-depth-estimation
channels:
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - tqdm
  - pytorch
  - torchvision
  - tqdm
  - pandas
  - pytorch-model-summary
  - pip
  - pip:
    - torch-summary


